### ISSUE TITLE
Python code hierarchy

### ISSUE THREAD

**Issue by smurfix** [sgjava/userspaceio#1]
This may be a stupid question, but why are you (essentially) using libgpiod.libgpiod.libgpiod().ffi/lib? IMHO there's no need for the class, nor for the additional submodule. Thus, `libgpiod.__init__.py` might simply contain 

```
from cffi import FFI
ffi = FFI()
ffi.cdef("""…""")
lib = ffi.dlopen("libgpiod.so")
```

**Comment by sgjava** [comment]
It's a good question. My intent was to use OOP and use a package for pip install (something like https://github.com/vsergeev/python-periphery). If you look at the I2C class https://github.com/sgjava/userspaceio/blob/master/c-periphery/python/src/libperiphery/libperipheryi2c.py you'll note there's added functionality provided by the added methods. Rather than mix OOP and non-OOP code I ended up standardizing on OOP.

http://docs.python-guide.org/en/latest/writing/structure

**Comment by sgjava** [comment]
I'm going to close this out for now.
