### ISSUE TITLE
Please support kernel 4.19

### ISSUE THREAD

**Issue by ufechner7** [sgjava/userspaceio#10]
Not everyone has the freedom to use kernel 5.x. 
Which changes would be needed to support kernel 4.19 ?

**Comment by sgjava** [comment]
So there's a couple things you can do. The easy way is to edit https://github.com/sgjava/userspaceio/blob/f387e92275d8e4b2b4183facfcf0db494788d039/libgpiod/install.sh#L11 and use v1.4.x instead of master before running install.sh.

Or use 5.5 kernel headers and use master branch. libgpiod will throw not supported exception for functions that are not supported under < 5.5 kernal.
