### ISSUE TITLE
Java 11?

### ISSUE THREAD

**Issue by geokon-gh** [sgjava/userspaceio#4]
Are there any plans to include support for Java 11?

I don't really have any experience with working with GPIO, but I was looking to try to dip my feet with the Nanopi Duo2 and Clojure. This seems like the only current effort to integrate GPIO with the JVM (jdk.dio seems pretty much dead)

**Comment by sgjava** [comment]
You should be able to use the Java 8 library in Java 11. The problem is [JNAerator](https://github.com/nativelibs4java/JNAerator) has only been tested in Java 8 personally. The last commit was 2015. I'll be looking at Java 11 for ARM. It looks like you'll have to use [Zulu](https://www.azul.com/downloads/zulu-embedded/) since Oracle doesn't appear to have a Java 11 release for ARM.

**Comment by geokon-gh** [comment]
I didn't know you can call one from the other :) I'll test it out. Sorry, I'm kinda new to the JVM ecosystem.

OpemJDK 11 has packages for ARM on Debian

https://packages.debian.org/buster/openjdk-11-jdk

or am I misunderstanding something?

**Comment by sgjava** [comment]
The beauty of byte code. With a few exceptions you can use Java 8 compiled jars with Java 8,9,10,11,12.
